# Generated by Django 5.1.4 on 2025-11-01 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiapp', '0005_userprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('cook', 'Cook'), ('user', 'User')], max_length=50),
        ),
    ]
