# Generated by Django 5.1.4 on 2025-11-09 22:00

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiapp', '0007_alter_userprofile_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mealplanentry',
            name='meal_type',
        ),
        migrations.AddField(
            model_name='mealplan',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mealplan',
            name='recipes',
            field=models.ManyToManyField(related_name='in_meal_plans', to='apiapp.recipe'),
        ),
        migrations.AddField(
            model_name='mealplan',
            name='user',
            field=models.ForeignKey(default='9fbec363-e036-4b35-bbdc-d92eafa2a54f', on_delete=django.db.models.deletion.CASCADE, related_name='meal_plans', to='apiapp.userprofile'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mealplanentry',
            name='ingredient_name',
            field=models.CharField(default='ingredient_name', max_length=255),
        ),
        migrations.AddField(
            model_name='mealplanentry',
            name='purchased',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='mealplanentry',
            name='quantity',
            field=models.FloatField(default=1),
        ),
        migrations.AddField(
            model_name='mealplanentry',
            name='unit',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='recipe',
            name='cook',
            field=models.ForeignKey(default='9fbec363-e036-4b35-bbdc-d92eafa2a54f', on_delete=django.db.models.deletion.CASCADE, related_name='recipes', to='apiapp.userprofile'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='mealplanentry',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='mealplanentry',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='mealplanentry',
            name='recipe',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='apiapp.recipe'),
        ),
    ]
